### ISSUE TITLE
Inconsistent application of CSS styles depending on element order

### ISSUE THREAD

**Issue by brianchirls** [NativeScript/nativescript-cli#402]
I've been playing around with the CSS of the "Tap the button" example and have seen inconsistent and puzzling results. It seems that the styles I'm writing are not applied to certain elements, depending on the order of the elements in the view.

Here is my modified CSS:

```css
Page {
	background-color: lightgray;
}

Label {
	color: white;
}

.message {
    font-size: 20;
    horizontal-align: center;
}

.title {
	text-align: center;

    font-size: 30;
    horizontal-align: center;
    margin: 20;
}

button {
	background-color: transparent;
	border: none;
	color: white;

    font-size: 42;
    horizontal-align: center;
}
```

And here's the original view XML:
```xml
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
  <StackLayout>
    <Label text="Tap the button" cssClass="title"/>
    <Button text="TAP" tap="{{ tapAction }}" />
    <Label text="{{ message }}" cssClass="message" textWrap="true"/>
  </StackLayout>
</Page>
```

In this view, the `.message` Label element does not have any of the styles applied - neither the class-scoped styles nor the element-scoped styles. The text is black, and it's not center-aligned.

![tns-css-broken](https://cloud.githubusercontent.com/assets/492291/6920818/d14624fe-d78e-11e4-8380-be3877bcc51b.png)

However, if I switch the xml around so the `.message` label is before the button, like so...
```xml
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
  <StackLayout>
    <Label text="Tap the button" cssClass="title"/>
    <Label text="{{ message }}" cssClass="message" textWrap="true"/>
    <Button text="TAP" tap="{{ tapAction }}" />
  </StackLayout>
</Page>
```

...then all the styles apply correctly to that label.
![tns-css-flipped](https://cloud.githubusercontent.com/assets/492291/6920844/01016cf8-d78f-11e4-8a26-a3ace97be78a.png)

But in neither case do any of the Button styles apply.

The screenshots are from iOS, but it's the same in Android.
