### ISSUE TITLE
HMR not firing on all class changes

### ISSUE THREAD

**Issue by codytooker** [NativeScript/nativescript-cli#4883]
**Environment**
 - CLI: 6.0
 - Cross-platform modules: 6.0.1
 - Android Runtime: 6.0.0
 - iOS Runtime: 6.0.1

**Describe the bug**

Simply create a component and style it with something like the following

```css
.label {
  padding-left: 10;
  background-color: red;
  color: white;
}
```

**To Reproduce**

If you edit the padding nothing will change in the app.  If you edit the background color and the padding only the background color will change.  Finally if you edit any other prop on the component the padding will update to its current listed value.

**Expected behavior**
Editing any styles should cause HMR to take effect.
