### ISSUE TITLE
yntaxError: The requested module 'sourcemap-codec' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.

### ISSUE THREAD

**Issue by carlosdelfino** [NativeScript/nativescript-cli#5659]
### Issue Description

When creating a new project with `ns create` and then executing `ns run android` I get the following message:

```
Searching for devices...
Copying template files...
Platform android successfully added. v8.2.2
Preparing project...
webpack is watching the files...
(node:63847) ExperimentalWarning: The ESM module loader is experimental.
file:///home/carlosdelfino/workspace/islamic-works/ns-referencia/node_modules/@angular/compiler-cli/bundles/chunk-K2Z44JHH.js:12
import { decode, encode } from "sourcemap-codec";
         ^^^^^^
SyntaxError: The requested module 'sourcemap-codec' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'sourcemap-codec';
const { decode, encode } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:136:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
    at async AngularWebpackPlugin.initializeCompilerCli (/home/carlosdelfino/workspace/islamic-works/ns-referencia/node_modules/@ngtools/webpack/src/ivy/plugin.js:529:35)
Executing webpack failed with exit code 1.
```

The same error is happening with a project that was just migrated with the `ns migrate` command

### Reproduction

ns create ns-referencia
ns run android

### Relevant log output (if applicable)

```shell
Searching for devices...
Copying template files...
Platform android successfully added. v8.2.2
Preparing project...
webpack is watching the files...
(node:63847) ExperimentalWarning: The ESM module loader is experimental.
file:///home/carlosdelfino/workspace/islamic-works/ns-referencia/node_modules/@angular/compiler-cli/bundles/chunk-K2Z44JHH.js:12
import { decode, encode } from "sourcemap-codec";
         ^^^^^^
SyntaxError: The requested module 'sourcemap-codec' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'sourcemap-codec';
const { decode, encode } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:136:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
    at async AngularWebpackPlugin.initializeCompilerCli (/home/carlosdelfino/workspace/islamic-works/ns-referencia/node_modules/@ngtools/webpack/src/ivy/plugin.js:529:35)
Executing webpack failed with exit code 1.
```

### Environment

```yaml
OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
CPU: (4) x64 Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
Shell: /bin/bash
node: 12.18.3
npm: 8.5.5
nativescript: Not Found

# android
java: 1.8.0_312
ndk: Not Found
apis: 28, 32
build_tools: 28.0.3, 32.0.0, 32.1.0
system_images: 
  - android-25 | Google APIs Intel x86 Atom_64
  - android-32 | Google Play Intel x86 Atom_64

# ios
xcode: Not Found
cocoapods: Not Found
python: 2.7.18
python3: 3.8.10
ruby: 3.1.1
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~13.2.0",
  "@angular/common": "~13.2.0",
  "@angular/compiler": "~13.2.0",
  "@angular/core": "~13.2.0",
  "@angular/forms": "~13.2.0",
  "@angular/platform-browser": "~13.2.0",
  "@angular/platform-browser-dynamic": "~13.2.0",
  "@angular/router": "~13.2.0",
  "@nativescript/angular": "^13.0.0",
  "@nativescript/core": "~8.2.0",
  "@nativescript/theme": "~3.0.2",
  "nativescript-ui-sidedrawer": "~10.0.2",
  "rxjs": "~7.5.0",
  "zone.js": "~0.11.5"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~13.2.0",
  "@angular/compiler-cli": "~13.2.0",
  "@nativescript/android": "8.2.2",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "~5.0.6",
  "@ngtools/webpack": "~13.2.0",
  "typescript": "~4.5.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
