### ISSUE TITLE
Unable to apply changes on device: . Error is: Could not start house arrest for application

### ISSUE THREAD

**Issue by mrwrighty** [NativeScript/nativescript-cli#5666]
### Issue Description

When using ns debug iOS --provision <Provisioning Profile Name> I get the following error:-

Unable to apply changes on device: ........ Error is: Could not start house arrest for application

Device ID removed for security. This seems to be a reoccurrence of an error back in 2019.

Application installs and runs, but no option to debug via Chrome

iOS Device is iPhone 6S running iOS 15.4.1

### Reproduction

ns debug iOS --provision <Provisioning Profile Name> 

### Relevant log output (if applicable)

```shell
Output is as per title.
```

### Environment

```yaml
OS: macOS 12.3
CPU: (8) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 17.6.0
npm: 8.5.1
nativescript: 8.2.3

# android
java: 1.8.0_172
ndk: Not Found
apis: 25, 27, 28
build_tools: 25.0.2, 27.0.3, 28.0.3
system_images: 
  - android-28 | Google APIs Intel x86 Atom

# ios
xcode: 13.3.1/13E500a
cocoapods: 1.11.2
python: 3.9.10
python3: 3.9.10
ruby: 2.6.8
platforms: 
  - DriverKit 21.4
  - iOS 15.4
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/gps": "^3.1.3",
  "@nativescript-community/sqlite": "^3.4.1",
  "@nativescript-community/ui-mapbox": "^6.2.15",
  "@nativescript/appavailability": "^2.0.0",
  "@nativescript/background-http": "^5.0.2",
  "@nativescript/camera": "^5.0.10",
  "@nativescript/core": "^8.1.5",
  "@nativescript/datetimepicker": "^2.1.9",
  "@nativescript/theme": "^3.0.2",
  "@nstudio/nativescript-cardview": "^2.0.1",
  "@proplugins/nativescript-drop-down": "^9.0.2",
  "@proplugins/nativescript-platform": "^1.4.15",
  "@triniwiz/nativescript-videorecorder": "^4.0.2",
  "nativescript": "^7.2.0",
  "nativescript-accelerometer": "^3.0.0",
  "nativescript-background-fetch": "^1.2.1",
  "nativescript-fresco": "^5.3.0",
  "nativescript-google-maps-sdk": "^3.0.2",
  "nativescript-intl": "^4.0.2",
  "nativescript-iqkeyboardmanager": "^1.5.1",
  "nativescript-sqlite": "^2.8.6",
  "nativescript-theme-core": "^2.0.24",
  "nativescript-ui-dataform": "^8.0.1",
  "nativescript-ui-listview": "^10.0.2",
  "nativescript-videoplayer": "^5.0.1",
  "reflect-metadata": "0.1.13",
  "rxjs": "6.5.4",
  "rxjs-compat": "6.5.4",
  "zone.js": "0.10.2"
},
"devDependencies": {
  "@nativescript/android": "~8.2.0",
  "@nativescript/ios": "~8.2.0",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "~5.0.0-beta.14",
  "@webpack-cli/generators": "^2.4.2",
  "copy-webpack-plugin": "^9.1.0",
  "typescript": "~4.3.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
