### ISSUE TITLE
Error in Live-reload

### ISSUE THREAD

**Issue by danishashraf047** [NativeScript/nativescript-cli#5670]
### Issue Description

When I run "ns run ios" then I'm not able to get live-reload and get the below error.
```
Refreshing application on device 00008020-001D301A1178002E...
__onLiveSync call failed
```

Expected Behaviour:
Live-reload must work.

### Reproduction

I also have updated the NativeScript version to the latest one which is 8.2.3. I'm using "@nativescript/ios": "8.2.3" iOS platform version.

### Relevant log output (if applicable)

```shell
Refreshing application on device 00008020-001D301A1178002E...
__onLiveSync call failed
```

### Environment

```yaml
OS: macOS 12.3.1
CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
Shell: /bin/zsh
node: 14.17.0
npm: 7.19.1
nativescript: 8.2.3

# android
java: 15.0.2
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.3.1/13E500a
cocoapods: 1.10.1
python: 3.7.9
python3: 3.7.9
ruby: 2.7.6
platforms: 
  - DriverKit 21.4
  - iOS 15.4
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {},
"devDependencies": {}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
What flavor, what kind of change, does `--no-hmr` work? (run the envinfo script in the project root to include dependencies/devDependencies)

**Comment by danishashraf047** [comment]
I'm using the NativeScript Core with TypeScript and the app runs fine with --no-hmr but getting the above error while running with Hot Module Replacement. I need to use hmr for live-reload. This the envinfo from the project root.

```yaml
OS: macOS 12.3.1
CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
Shell: /bin/zsh
node: 14.17.0
npm: 7.19.1
nativescript: 8.2.3

# android
java: 15.0.2
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.3.1/13E500a
cocoapods: 1.10.1
python: 3.7.9
python3: 3.7.9
ruby: 2.7.6
platforms: 
  - DriverKit 21.4
  - iOS 15.4
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/https": "^3.3.13",
  "@nativescript-community/perms": "^2.1.8",
  "@nativescript-community/ui-document-picker": "^1.1.6",
  "@nativescript-community/ui-lottie": "^4.1.2",
  "@nativescript-community/ui-material-bottom-navigation": "^6.1.2",
  "@nativescript-community/ui-material-bottomsheet": "^5.3.21",
  "@nativescript-community/ui-material-tabs": "^6.0.3",
  "@nativescript-community/ui-pager": "^13.0.31",
  "@nativescript-community/ui-pulltorefresh": "^2.5.0",
  "@nativescript/background-http": "^5.0.2",
  "@nativescript/core": "~8.1.1",
  "@nativescript/firebase": "^11.1.3",
  "@nativescript/geolocation": "^7.2.1",
  "@nativescript/localize": "^5.0.4",
  "@nativescript/theme": "~2.3.0",
  "@nstudio/nativescript-checkbox": "^2.0.4",
  "@nstudio/nativescript-loading-indicator": "^4.0.0",
  "@nstudio/nativescript-snackbar": "^2.1.0",
  "@proplugins/nativescript-localstorage": "^2.3.2",
  "@proplugins/nativescript-platform-css": "^1.8.0",
  "@types/uuid": "^8.3.1",
  "@xmpp/client": "0.9.2",
  "axios": "^0.26.0",
  "jwt-decode": "^3.1.2",
  "moment": "^2.29.1",
  "nativescript-audio": "^6.2.5",
  "nativescript-carousel": "^7.0.1",
  "nativescript-dna-deviceinfo": "^3.7.1",
  "nativescript-drop-down": "^6.0.0",
  "nativescript-exit": "^1.0.1",
  "nativescript-iqkeyboardmanager": "^1.3.0",
  "nativescript-na-keyboard": "^1.1.0",
  "nativescript-numeric-keyboard": "^5.0.2",
  "nativescript-onesignal-sdk": "^1.0.0",
  "nativescript-ui-listview": "^10.0.1",
  "rxjs": "^7.4.0",
  "uuid": "^3.0.1"
},
"devDependencies": {
  "@babel/core": "^7.0.0",
  "@nativescript/android": "8.1.1",
  "@nativescript/ios": "8.2.3",
  "@nativescript/types": "^8.0.1",
  "@nativescript/webpack": "~5.0.0",
  "babel-loader": "^8.0.6",
  "sass": "~1.39.0",
  "tslint": "~5.19.0",
  "typescript": "~4.3.5"
}
```
