### ISSUE TITLE
✖ WARNING: CocoaPods is not installed or is not configured properly (when cocoapods is installed)

### ISSUE THREAD

**Issue by JimLynchCodes** [NativeScript/nativescript-cli#5688]
### Issue Description

when I run `tns doctor ios`

```
I get this error (it says warning, but it prevents builds from happening...)

✖ WARNING: CocoaPods is not installed or is not configured properly. 
 You will not be able to build your projects for iOS if they contain plugin with CocoaPod file.
To be able to build such projects, verify that you have installed CocoaPods (`sudo gem install cocoapods`). 

Your environment is not configured properly and you will not be able to execute local builds.
Verify that your environment is configured according to the system requirements described at
https://docs.nativescript.org/environment-setup.html#macos-ios.
```

The link there is not helpful.

I already ran `sudo gem install cocoapods`, and I can see that it is installed because when I run `pod` I see all the cocoapods commands...

when I run `which pod` it says this: `/Users/jim/.nvm/versions/node/v13.13.0/bin/pod`

Why does tns not see my cocoapods installed, and wtf do I do to make it work?? 😢
 

### Reproduction

tns doctor ios

### Environment

```yaml
OS: macOS 12.4
CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
Shell: /bin/zsh
node: 13.13.0
npm: 6.14.4
nativescript: 8.2.3

# android
java: Not Found
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.4.1/13F100
cocoapods: Not Found
python: 3.9.13
python3: 3.9.13
ruby: 2.6.8
platforms: 
  - DriverKit 21.4
  - iOS 15.5
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~8.2.0",
  "@angular/common": "~8.2.0",
  "@angular/compiler": "~8.2.0",
  "@angular/core": "~8.2.0",
  "@angular/forms": "~8.2.0",
  "@angular/platform-browser": "~8.2.0",
  "@angular/platform-browser-dynamic": "~8.2.0",
  "@angular/router": "~8.2.0",
  "@nativescript/theme": "~2.3.0",
  "nativescript-angular": "~8.21.0",
  "nativescript-auth0": "^3.0.2",
  "nativescript-plugin-firebase": "^10.6.3",
  "nativescript-ui-sidedrawer": "~8.0.0",
  "reflect-metadata": "~0.1.12",
  "rxjs": "^6.4.0",
  "tns-core-modules": "~6.5.0",
  "zone.js": "~0.9.1"
},
"devDependencies": {
  "@angular/compiler-cli": "~8.2.0",
  "@nativescript/schematics": "^9.0.0",
  "@ngtools/webpack": "~8.2.0",
  "codelyzer": "~4.5.0",
  "nativescript-angular-cli": "^0.1.9",
  "nativescript-dev-webpack": "~1.5.0",
  "node-sass": "^4.7.1",
  "tns-ios": "6.5.3",
  "tslint": "~5.19.0",
  "typescript": "~3.5.3"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
