### ISSUE TITLE
NS + Angular | IOS Simulator stuck on NativeScript Splash or black app screen

### ISSUE THREAD

**Issue by ThijmenL98** [NativeScript/nativescript-cli#5696]
### Issue Description

When i try to launch the created app on my ios simulator on my MacBook Pro, it gets stuck on a black screen when opening the app (iPhone) or on the blue NativeScript launch screen (iPad).

The app in question is simply a single screen with an input field, button and a text field that copies the input field text to the text field when clicking the button. The only CSS used is to make the button coloured and the displayed text centered and bold.

Have tried:
- Restarting MacBook Pro
- Restarting Simulator
- Changing Simulator device
- Deleting node_modules folder and running npm install
- Invalidating IntelliJ caches
- Shaking device
- Erasing all content and settings from device

### Reproduction

'tns run ios --bundle'

### Environment

```yaml
OS: macOS 12.6
CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
Shell: /bin/zsh
node: 18.11.0
npm: 8.19.2
nativescript: 8.3.3

# android
java: 11.0.17
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.0.1/14A400
cocoapods: 1.11.3
python: 3.10.8
python3: 3.10.8
ruby: 2.7.6
platforms: 
  - DriverKit 21.4
  - iOS 16.0
  - macOS 12.3
  - tvOS 16.0
  - watchOS 9.0


### Dependencies

json
"dependencies": {},
"devDependencies": {
  "tslint": "^6.1.3",
  "typescript": "^4.8.4"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
