### ISSUE TITLE
iTMS Transporter not found on this machine - Transporter is no longer bundled with xcode 14

### ISSUE THREAD

**Issue by BjornGameDev** [NativeScript/nativescript-cli#5704]
### Issue Description

When you try to publish a ios app on Xcode 14 it throws the following error:

```
iTMS Transporter not found on this machine - make sure your Xcode installation is not damaged.
```

The transporter app is no longer bundled with Xcode 14? One fix I found is to install the Transporter.app separately from the App store and hard code  getITMSTransporterPath function in itmtransporter-service.js to '/Applications/Transporter.app/Contents/itms/bin/iTMSTransporter'.

### Reproduction

With xcode 14 and MacOs Ventura

1. Run ns publish ios
2. Throws error iTMS Transporter not found on this machine - make sure your Xcode installation is not damaged.

### Environment

```yaml
OS: macOS 13.0
CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
Shell: /bin/zsh
node: 12.9.1
npm: 6.10.2
nativescript: 8.3.3

# android
java: 11.0.14.1
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.0.1/14A400
cocoapods: 1.11.2
python: 2.7.18
python3: 3.8.6
ruby: 2.6.10
platforms:
  - DriverKit 21.4
  - iOS 16.0
  - macOS 12.3
  - tvOS 16.0
  - watchOS 9.0
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
