### ISSUE TITLE
ns typings command error "parse error near `\n'"

### ISSUE THREAD

**Issue by ad-proximate** [NativeScript/nativescript-cli#5708]
### Issue Description

I have a really small kotlin library to test how to import it into nativescript. I followed the steps of this page:
[https://blog.nativescript.org/how-to-use-java-code-in-nativescript/](https://blog.nativescript.org/how-to-use-java-code-in-nativescript/ )
I've fallen down at the step when creating typings for ns. I'm getting always the same error: zsh: parse error near \n'`

### Reproduction

The kotlin class:

`package com.example.mytestlibrary

class MyFirst {
    fun getMySentence(): String {
        return "Lorem Ipsum"
    }
}`

I've built an .aar (attached) from the lib in Android Studio and unziped to access the jar file and put the files into NS project.

[MyTestLibrary.aar.zip](https://github.com/NativeScript/nativescript-cli/files/10183479/MyTestLibrary.aar.zip)

If I run ns typings android –-jar <./libs/MyTestLibrary/classes.jar> I get this error: zsh: parse error near `\n'

I can't find out why?

### Relevant log output (if applicable)

```shell
zsh: parse error near `\n'
```

### Environment

```yaml
OS: macOS 13.0.1
CPU: (8) arm64 Apple M2
Shell: /bin/zsh
node: 16.18.0
npm: 8.19.2
nativescript: 8.3.3

# android
java: 11.0.16.1
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: /undefined
cocoapods: 1.11.3
python: 3.10.8
python3: 3.10.8
ruby: 2.6.10
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~15.0.0",
  "@angular/common": "~15.0.0",
  "@angular/compiler": "~15.0.0",
  "@angular/core": "~15.0.0",
  "@angular/forms": "~15.0.0",
  "@angular/platform-browser": "~15.0.0",
  "@angular/platform-browser-dynamic": "~15.0.0",
  "@angular/router": "~15.0.0",
  "@nativescript/angular": "~15.0.0",
  "@nativescript/core": "~8.4.0",
  "@nativescript/theme": "~3.0.2",
  "rxjs": "~7.5.0",
  "zone.js": "~0.11.5"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~15.0.0",
  "@angular/cli": "^15.0.2",
  "@angular/compiler-cli": "~15.0.0",
  "@nativescript/android": "8.3.1",
  "@nativescript/types": "~8.4.0",
  "@nativescript/webpack": "~5.0.12",
  "@ngtools/webpack": "~15.0.0",
  "typescript": "~4.8.4"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
