### ISSUE TITLE
tns apple-login sms verification doesn't work

### ISSUE THREAD

**Issue by ralyodio** [NativeScript/nativescript-cli#5714]
### Issue Description

`tns apple-login` fails with sms verification

```
$ tns apple-login      
✔ Apple ID … me@example.com
✔ Apple ID password … ************
✔ Please enter the 6 digit code … 955316
Request failed with status code 400
```

### Reproduction

use `tns apple-login` command from macbook air.

### Environment

$ npm i -D nativescript-envinfo

added 2 packages, and audited 454 packages in 2s

50 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
➜  calmness-mobile git:(main) ✗ 
$ npx nativescript-envinfo 

```yaml
OS: macOS 12.6.3
CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
Shell: /bin/zsh
node: 16.17.0
npm: 8.15.0
nativescript: 8.3.3

# android
java: Not Found
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.4.1/13F100
cocoapods: 1.11.3
python: 3.10.6
python3: 3.10.6
ruby: 2.7.6
platforms: 
  - DriverKit 21.4
  - iOS 15.5
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "~8.1.3",
  "@nativescript/theme": "^3.0.2",
  "@triniwiz/nativescript-couchbase": "^1.3.1",
  "@triniwiz/nativescript-image-cache-it": "^7.0.21",
  "@triniwiz/nativescript-toasty": "^4.1.3",
  "nativescript-audio": "^6.2.6",
  "nativescript-platform-free": "^1.3.2",
  "svelte-gestures": "^1.4.1",
  "svelte-native": "~1.0.5"
},
"devDependencies": {
  "@nativescript/android": "^8.4.0",
  "@nativescript/ios": "^8.3.3",
  "@nativescript/preview-cli": "^1.0.0-beta.18",
  "@nativescript/types": "^8.3.0",
  "@nativescript/webpack": "^5.0.6",
  "nativescript-envinfo": "^1.0.9",
  "svelte": "~3.44.0",
  "svelte-loader": "^3.1.2",
  "svelte-native-preprocessor": "^1.0.0",
  "svelte-preprocess": "^4.7.0",
  "typescript": "^4.5.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
