### ISSUE TITLE
webpack.config.js does not exist

### ISSUE THREAD

**Issue by vallemar** [NativeScript/nativescript-cli#5731]
### Issue Description

I have a new project and when run `ns run android` I have this error:
```
The webpack configuration file /xxxx/ns-bank-cards/webpack.config.js does not exist. Ensure the file exists, or update the path in nativescript.config.(js|ts).
```

I am using the new cli nativescript@8.5.3
```
vallemar@macbook-pro-de-juan bank-cards % ns -v
8.5.3
✔ Up to date.
```

### Environment

```yaml
OS: macOS 13.3
CPU: (12) arm64 Apple M2 Max
Shell: /bin/zsh
node: 18.14.0
npm: 9.3.1
nativescript: 8.5.3

# android
java: 11.0.18
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.3/14E222b
cocoapods: 1.11.3
python: 3.10.10
python3: 3.10.10
ruby: 2.7.7
platforms: 
  - DriverKit 22.4
  - iOS 16.4
  - macOS 13.3
  - tvOS 16.4
  - watchOS 9.4
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "^8.5.0",
  "nativescript-vue": "3.0.0-beta.5"
},
"devDependencies": {
  "@nativescript-dom/core-types": "^1.0.25",
  "@nativescript-dom/vue-types": "^1.0.14",
  "@nativescript/android": "8.5.0",
  "@nativescript/tailwind": "^2.0.1",
  "@nativescript/types": "~8.4.0",
  "@nativescript/webpack": "~5.0.0",
  "@types/node": "~17.0.21",
  "tailwindcss": "^3.1.8",
  "typescript": "~4.8.4",
  "vue": "^3.2.45"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
