### ISSUE TITLE
type generation of gradle package on windows

### ISSUE THREAD

**Issue by KG3RK3N** [NativeScript/nativescript-cli#5810]
### Issue Description

Run the following command on a windows machine: `ns typings android <package-name>`
That always results into the message:
```
No .jar or .aar file specified. Please specify at least one of the following:
  - path to .jar file with --jar <jar>
  - path to .aar file with --aar <aar>
```

Solution: Replace hard coded split char `"/"` to `path.sep`
https://github.com/NativeScript/nativescript-cli/blob/bf9a6cdbed227c876b8a94a13e3517e684dad924/lib/commands/typings.ts#L80C62-L80C65

### Reproduction

Run `ns typings android <package-name>` on a windows machine

### Environment

```yaml
OS: Windows 11 10.0.22631
CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics
Shell: Not Found
node: 20.15.0
npm: 10.7.0
nativescript: Not Found

# android
java: Not Found
ndk: Not Found
apis: 22, 25, 26, 27, 28, 29, 30, 31, 32, 33, 33, 34, 35
build_tools: 27.0.3, 28.0.2, 28.0.3, 29.0.1, 29.0.2, 30.0.0, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.2, 34.0.0, 35.0.0
system_images:
  - android-22 | Google APIs Intel x86 Atom
  - android-26 | Google APIs Intel x86 Atom
  - android-27 | Google APIs Intel x86 Atom
  - android-27 | Google Play Intel x86 Atom
  - android-28 | Google APIs Intel x86 Atom
  - android-29 | Intel x86 Atom
  - android-29 | Google APIs Intel x86 Atom
  - android-30 | Google APIs Intel x86 Atom
  - android-31 | Google APIs Intel x86_64 Atom
  - android-33 | Google Play Intel x86_64 Atom
  - android-34 | Google Play Intel x86_64 Atom

# ios
xcode: Not Found
cocoapods: Not Found
python: Not Found
python3: Not Found
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~18.0.0",
  "@angular/common": "~18.0.0",
  "@angular/compiler": "~18.0.0",
  "@angular/core": "~18.0.0",
  "@angular/forms": "~18.0.0",
  "@angular/platform-browser": "~18.0.0",
  "@angular/platform-browser-dynamic": "~18.0.0",
  "@angular/router": "~18.0.0",
  "@nativescript-community/md5": "^1.0.4",
  "@nativescript-community/perms": "^2.3.3",
  "@nativescript-community/ui-checkbox": "^2.0.12",
  "@nativescript-community/ui-material-bottom-navigation": "^7.2.61",
  "@nativescript-community/ui-material-bottomsheet": "^7.2.61",
  "@nativescript-community/ui-material-snackbar": "^7.2.61",
  "@nativescript-community/ui-pulltorefresh": "^2.5.3",
  "@nativescript/angular": "^18.0.0",
  "@nativescript/appversion": "^2.0.0",
  "@nativescript/background-http": "^6.0.1",
  "@nativescript/core": "^8.8.2",
  "@nativescript/datetimepicker": "^3.0.0",
  "@nativescript/geolocation": "^9.0.0",
  "@nativescript/imagepicker": "^4.0.0",
  "@nativescript/picker": "^4.1.0",
  "@nativescript/theme": "~3.1.0",
  "@ngrx/signals": "^18.0.0",
  "@ngx-translate/core": "^15.0.0",
  "@nstudio/nativescript-loading-indicator": "^4.3.4",
  "@triniwiz/nativescript-couchbase": "^1.4.0",
  "@triniwiz/nativescript-downloader": "^3.1.0",
  "@triniwiz/nativescript-toasty": "^4.1.3",
  "@triniwiz/nativescript-tooltip": "^3.0.0",
  "@turf/turf": "6.5",
  "@types/luxon": "^1.27.1",
  "@types/mime": "^4.0.0",
  "@types/semver": "^7.5.8",
  "geojson": "^0.5.0",
  "js-base64": "^3.7.7",
  "loglevel": "^1.9.1",
  "luxon": "<2.0.0",
  "mime": "^4.0.4",
  "nativescript-android-sensors": "^2.1.0",
  "nativescript-intl": "^4.0.2",
  "nativescript-ui-listview": "^15.2.3",
  "rxjs": "^7.5.7",
  "semver": "^7.6.3",
  "typed-local-store": "^2.0.2",
  "zone.js": "~0.14.0"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~18.0.0",
  "@angular/compiler-cli": "~18.0.0",
  "@eslint/js": "^9.8.0",
  "@nativescript/android": "8.8.2",
  "@nativescript/types": "^8.8.0",
  "@nativescript/webpack": "^5.0.22",
  "@ngtools/webpack": "~18.0.0",
  "@types/lodash": "^4.17.7",
  "eslint": "^9.8.0",
  "eslint-plugin-unused-imports": "^4.0.1",
  "globals": "^15.8.0",
  "husky": "^8.0.1",
  "lint-staged": "^15.2.7",
  "properties-reader": "^2.3.0",
  "tslint": "^6.1.3",
  "typescript": "~5.4.0",
  "typescript-eslint": "^7.17.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
