### ISSUE TITLE
Global variables not defined in CLI 8.8

### ISSUE THREAD

**Issue by asharghi** [NativeScript/nativescript-cli#5813]
### Issue Description

After bumping packages, I found that some packages/plugins only work when I uninstall ns cli globally and install "nativescript": "8.7.2" (downgrade from cli 8.8). 

### Reproduction

https://github.com/asharghi/print-star-demo

1. Clone and run with 'ns run iOS' with CLI 8.8
2. Tap on "Test" button and see "Error" in the console log
3. Uninstall CLI 8.8 and install CLI 8.7.2
4. Run 'ns clean && ns run ios'
5. Tap on "Test" button again and see "Success" in the console log

### Environment

```yaml
OS: macOS 14.6.1
CPU: (10) arm64 Apple M1 Max
Shell: /bin/zsh
node: 18.18.1
npm: 9.8.1
nativescript: Not Found

# android
java: 17.0.11
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 15.3/15E204a
cocoapods: 1.15.2
python: 2.7.18
python3: 3.12.4
ruby: 2.7.8
platforms: 
  - DriverKit 23.4
  - iOS 17.4
  - macOS 14.4
  - tvOS 17.4
  - visionOS 1.1
  - watchOS 10.4
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/perms": "^2.3.3",
  "@nativescript/core": "~8.8.0",
  "@nativescript/theme": "^3.1.0",
  "nativescript": "8.7.2",
  "nativescript-permissions": "^1.3.12",
  "nativescript-print-star": "file:local_modules/nativescript-print-star-latest.tgz",
  "nativescript-vue": "~2.9.3"
},
"devDependencies": {
  "@nativescript/ios": "8.8.1",
  "@nativescript/types": "~8.8.0",
  "@nativescript/webpack": "~5.0.0",
  "@types/node": "~17.0.21",
  "nativescript-vue-template-compiler": "~2.9.3",
  "typescript": "~5.4.0",
  "vue": "~2.6.12"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
